message(STATUS "Host system: ${CMAKE_HOST_SYSTEM}")
message(STATUS "Build version: ${${MODULE_NAME}_VERSION}")
message(STATUS "Target vendor: ${${MODULE_NAME}_TARGET_VENDOR}")
message(STATUS "Platform: ${PLATFORM}")
message(STATUS "Target: ${TARGET_ABI}")
message(STATUS "Build type: ${CMAKE_BUILD_TYPE}")
message(STATUS "Toolchain: ${CMAKE_TOOLCHAIN_FILE}")
message(STATUS "Toolchain option: ${TOOLCHAIN_OPTION}")
message(STATUS "c flags: ${CMAKE_C_FLAGS}")
message(STATUS "c flags (debug): ${CMAKE_C_FLAGS_DEBUG}")
message(STATUS "c flags (release): ${CMAKE_C_FLAGS_RELEASE}")
message(STATUS "c link flags: ${CMAKE_C_LINK_FLAGS}")
message(STATUS "c++ flags: ${CMAKE_CXX_FLAGS}")
message(STATUS "c++ flags (debug): ${CMAKE_CXX_FLAGS_DEBUG}")
message(STATUS "c++ flags (release): ${CMAKE_CXX_FLAGS_RELEASE}")
message(STATUS "c++ link flags: ${CMAKE_CXX_LINK_FLAGS}")
if(ANDROID)
    message(STATUS "Android STL Library: ${ANDROID_STL}")
endif()
if(USE_CUDA)
    message(STATUS "nvcc flags: ${CUDA_NVCC_FLAGS}")
    message(STATUS "nvcc flags (debug): ${CUDA_NVCC_FLAGS_DEBUG}")
    message(STATUS "nvcc flags (release): ${CUDA_NVCC_FLAGS_RELEASE}")
endif()
